### ISSUE TITLE
output_path 디렉토리 폴더 없는 경우 에러

### ISSUE THREAD

**Issue by parkhojeong** [yoonji-jang/YoutubeParser#1]
`/data` 을 미리 만들어두지 않을 경우 프로그램이 중단되는 문제가 있어 수정이 필요합니다 
- 실행환경: mac

![image](https://user-images.githubusercontent.com/34734102/130351832-0b902ad7-8f4f-4119-9304-79fec8ee26d6.png)

**Comment by yoonji-jang** [comment]
output file을 input.txt 로 입력받도록 수정했습니다.
