### ISSUE TITLE
path에서 window os에 대한 dependency 제거

### ISSUE THREAD

**Issue by parkhojeong** [yoonji-jang/YoutubeParser#2]
경로 중 윈도우에 의존적인 코드가 있어서 unix 계열에서 실행이 되지 않습니다.
`os.path`등을 이용하여 mac 등 에서도 돌아가도록 수정이 필요합니다
`driver = wd.Chrome(executable_path=".\\chromedriver_win32\\chromedriver.exe", ...)`

**Comment by yoonji-jang** [comment]
cf614821a01a3e7db325475c15d5731dc7795ebb commit 에서 local path 제거했습니다
